baseURL: 'https://yetanotherblog.me'
languageCode: ru-RU
title: Еще один блог
enableEmoji: true
taxonomies:
  tag: tags

menu:
  main:
  - name: Статьи
    url: /posts
#  - name: Доклады
#    url: /talks
#  - name: Проекты
#    url: /projects

markup:
  tableOfContents:
    ordered: false
